"""
Eagle Strategies: Trading Strategy Framework
===============================================
Plugin-based strategy system with base class, built-in strategies
(momentum, mean reversion, ML-driven), and a strategy manager.
"""

from __future__ import annotations

import logging
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any

import numpy as np
import pandas as pd

from eagle.core.config import EagleConfig
from eagle.core.events import EventBus
from eagle.models.base_model import Prediction, Signal

logger = logging.getLogger(__name__)


class OrderSide(Enum):
    BUY = "buy"
    SELL = "sell"


@dataclass
class TradeSignal:
    """A trade signal generated by a strategy."""

    symbol: str
    side: OrderSide
    strength: float  # -1.0 to 1.0
    confidence: float  # 0.0 to 1.0
    strategy_name: str
    timestamp: datetime = field(default_factory=datetime.utcnow)
    metadata: dict[str, Any] = field(default_factory=dict)
    stop_loss: float | None = None
    take_profit: float | None = None
    size_hint: float | None = None  # Suggested position size as fraction

    @property
    def is_buy(self) -> bool:
        return self.side == OrderSide.BUY

    @property
    def is_sell(self) -> bool:
        return self.side == OrderSide.SELL


class BaseStrategy(ABC):
    """Abstract base class for all trading strategies."""

    def __init__(self, name: str, config: EagleConfig) -> None:
        self.name = name
        self.config = config
        self._active = True

    @abstractmethod
    def generate_signals(
        self,
        market_data: pd.DataFrame,
        features: pd.DataFrame,
        predictions: list[Prediction] | None = None,
    ) -> list[TradeSignal]:
        """Generate trading signals from market data and features."""
        ...

    @property
    def is_active(self) -> bool:
        return self._active

    def activate(self) -> None:
        self._active = True

    def deactivate(self) -> None:
        self._active = False


class MomentumStrategy(BaseStrategy):
    """
    Momentum/Trend-following strategy.

    Buys when price momentum exceeds entry threshold,
    sells when momentum falls below exit threshold.
    Uses multiple timeframe confirmation.
    """

    def __init__(self, config: EagleConfig) -> None:
        super().__init__("momentum", config)
        self._cfg = config.strategies.momentum

    def generate_signals(
        self,
        market_data: pd.DataFrame,
        features: pd.DataFrame,
        predictions: list[Prediction] | None = None,
    ) -> list[TradeSignal]:
        signals: list[TradeSignal] = []

        for symbol in market_data["symbol"].unique() if "symbol" in market_data.columns else [""]:
            sym_data = market_data[market_data["symbol"] == symbol] if symbol else market_data
            sym_feat = features.loc[sym_data.index] if not features.empty else features

            if len(sym_data) < self._cfg.lookback_period:
                continue

            close = sym_data["close"]
            ret = close.pct_change(self._cfg.lookback_period).iloc[-1]

            # Confirmation via moving average alignment
            sma_20 = sym_feat.get("sma_20")
            sma_50 = sym_feat.get("sma_50")
            rsi = sym_feat.get("rsi")

            ma_aligned = True
            if sma_20 is not None and sma_50 is not None:
                ma_aligned = sma_20.iloc[-1] > sma_50.iloc[-1] if ret > 0 else sma_20.iloc[-1] < sma_50.iloc[-1]

            rsi_ok = True
            if rsi is not None:
                rsi_val = rsi.iloc[-1]
                if ret > 0 and rsi_val > 80:
                    rsi_ok = False  # Overbought
                if ret < 0 and rsi_val < 20:
                    rsi_ok = False  # Oversold

            if ret > self._cfg.entry_threshold and ma_aligned and rsi_ok:
                signals.append(TradeSignal(
                    symbol=symbol,
                    side=OrderSide.BUY,
                    strength=min(ret / self._cfg.entry_threshold, 2.0) / 2.0,
                    confidence=0.6 if ma_aligned else 0.4,
                    strategy_name=self.name,
                    stop_loss=close.iloc[-1] * (1 - self.config.risk.stop_loss_pct),
                    take_profit=close.iloc[-1] * (1 + self.config.risk.take_profit_pct),
                ))
            elif ret < self._cfg.exit_threshold and ma_aligned:
                signals.append(TradeSignal(
                    symbol=symbol,
                    side=OrderSide.SELL,
                    strength=min(abs(ret) / abs(self._cfg.exit_threshold), 2.0) / 2.0,
                    confidence=0.6,
                    strategy_name=self.name,
                ))

        return signals


class MeanReversionStrategy(BaseStrategy):
    """
    Mean reversion strategy based on z-score of price deviations.

    Buys when z-score falls below negative threshold (oversold),
    sells when z-score rises above positive threshold (overbought).
    """

    def __init__(self, config: EagleConfig) -> None:
        super().__init__("mean_reversion", config)
        self._cfg = config.strategies.mean_reversion

    def generate_signals(
        self,
        market_data: pd.DataFrame,
        features: pd.DataFrame,
        predictions: list[Prediction] | None = None,
    ) -> list[TradeSignal]:
        signals: list[TradeSignal] = []

        for symbol in market_data["symbol"].unique() if "symbol" in market_data.columns else [""]:
            sym_data = market_data[market_data["symbol"] == symbol] if symbol else market_data

            if len(sym_data) < self._cfg.lookback_period:
                continue

            close = sym_data["close"]
            mean = close.rolling(self._cfg.lookback_period).mean()
            std = close.rolling(self._cfg.lookback_period).std()
            z = ((close - mean) / std.replace(0, np.nan)).iloc[-1]

            if np.isnan(z):
                continue

            # Buy when oversold
            if z <= -self._cfg.entry_z_score:
                strength = min(abs(z) / self._cfg.entry_z_score, 2.0) / 2.0
                signals.append(TradeSignal(
                    symbol=symbol,
                    side=OrderSide.BUY,
                    strength=strength,
                    confidence=min(abs(z) / 3.0, 1.0),
                    strategy_name=self.name,
                    stop_loss=close.iloc[-1] * (1 - self.config.risk.stop_loss_pct * 1.5),
                    take_profit=mean.iloc[-1],  # Target the mean
                    metadata={"z_score": z},
                ))

            # Sell when overbought
            elif z >= self._cfg.entry_z_score:
                strength = min(z / self._cfg.entry_z_score, 2.0) / 2.0
                signals.append(TradeSignal(
                    symbol=symbol,
                    side=OrderSide.SELL,
                    strength=strength,
                    confidence=min(z / 3.0, 1.0),
                    strategy_name=self.name,
                    metadata={"z_score": z},
                ))

        return signals


class MLStrategy(BaseStrategy):
    """
    ML-driven strategy that translates model predictions into trade signals.

    Uses the active ML model (ensemble by default) predictions as
    the primary signal source. Scales position size by confidence level.
    """

    def __init__(self, config: EagleConfig) -> None:
        super().__init__("ml_strategy", config)
        self._cfg = config.strategies.ml_strategy

    def generate_signals(
        self,
        market_data: pd.DataFrame,
        features: pd.DataFrame,
        predictions: list[Prediction] | None = None,
    ) -> list[TradeSignal]:
        if not predictions:
            return []

        signals: list[TradeSignal] = []
        symbols = market_data["symbol"].unique() if "symbol" in market_data.columns else ["UNKNOWN"]

        for i, pred in enumerate(predictions):
            if pred.confidence < self._cfg.min_confidence:
                continue

            symbol = pred.symbol if pred.symbol else (symbols[i % len(symbols)] if i < len(symbols) else symbols[-1])

            # Get current price for stop/take-profit calculation
            sym_data = market_data[market_data["symbol"] == symbol] if "symbol" in market_data.columns else market_data
            current_price = sym_data["close"].iloc[-1] if not sym_data.empty else 0

            if pred.signal in (Signal.BUY, Signal.STRONG_BUY):
                size_hint = pred.confidence if self._cfg.position_scale_by_confidence else None
                signals.append(TradeSignal(
                    symbol=symbol,
                    side=OrderSide.BUY,
                    strength=pred.confidence,
                    confidence=pred.confidence,
                    strategy_name=self.name,
                    stop_loss=current_price * (1 - self.config.risk.stop_loss_pct) if current_price else None,
                    take_profit=current_price * (1 + self.config.risk.take_profit_pct) if current_price else None,
                    size_hint=size_hint,
                    metadata={
                        "model": pred.model_name,
                        "predicted_return": pred.predicted_return,
                        "signal_type": pred.signal.name,
                    },
                ))

            elif pred.signal in (Signal.SELL, Signal.STRONG_SELL):
                signals.append(TradeSignal(
                    symbol=symbol,
                    side=OrderSide.SELL,
                    strength=pred.confidence,
                    confidence=pred.confidence,
                    strategy_name=self.name,
                    metadata={
                        "model": pred.model_name,
                        "predicted_return": pred.predicted_return,
                        "signal_type": pred.signal.name,
                    },
                ))

        return signals


class StrategyManager:
    """
    Manages all trading strategies and aggregates signals.

    Routes market data to active strategies, collects signals,
    and handles strategy lifecycle.
    """

    def __init__(self, config: EagleConfig, event_bus: EventBus) -> None:
        self.config = config
        self.event_bus = event_bus
        self._strategies: dict[str, BaseStrategy] = {}

    def initialize(self) -> None:
        """Initialize strategies based on configuration."""
        strategy_registry: dict[str, type[BaseStrategy]] = {
            "momentum": MomentumStrategy,
            "mean_reversion": MeanReversionStrategy,
            "ml_strategy": MLStrategy,
        }

        for name in self.config.strategies.active_strategies:
            if name in strategy_registry:
                self._strategies[name] = strategy_registry[name](self.config)
                logger.info(f"Strategy '{name}' activated")
            else:
                logger.warning(f"Unknown strategy: {name}")

    def register_strategy(self, name: str, strategy: BaseStrategy) -> None:
        """Register a custom strategy plugin."""
        self._strategies[name] = strategy
        logger.info(f"Custom strategy '{name}' registered")

    def generate_signals(
        self,
        market_data: pd.DataFrame,
        features: pd.DataFrame,
        predictions: list[Prediction] | None = None,
    ) -> list[TradeSignal]:
        """Generate signals from all active strategies."""
        all_signals: list[TradeSignal] = []

        for name, strategy in self._strategies.items():
            if not strategy.is_active:
                continue

            try:
                signals = strategy.generate_signals(market_data, features, predictions)
                all_signals.extend(signals)
                if signals:
                    logger.info(f"Strategy '{name}' generated {len(signals)} signals")
            except Exception as e:
                logger.error(f"Strategy '{name}' error: {e}", exc_info=True)

        return all_signals

    @property
    def active_strategies(self) -> list[str]:
        return [n for n, s in self._strategies.items() if s.is_active]
